---

- name: Certificates | Checking config
  ansible.builtin.fail:
    msg: "The required configuration was not provided!
    Needed: 'certs'"
  when: certs is undefined

- name: Certificates | Internal signed
  ansible.builtin.include_tasks: internal/main.yml
  when: "CERT_CONFIG.mode in ['pki', 'ca', 'selfsigned']"

- name: Certificates | Internal | CA
  ansible.builtin.include_tasks: debian/pki.yml
  when: CERT_CONFIG.mode == 'pki'

- name: Certificates | Debian | Letsencrypt
  ansible.builtin.include_tasks: debian/letsencrypt/main.yml
  when:
    - CERT_CONFIG.mode == 'le_certbot'
    - "ansible_distribution|lower in ['debian', 'ubuntu']"
