---

- name: Certificates | Checking config
  ansible.builtin.assert:
    that:
      - certs is defined

- name: Certificates | Showing debug info - user provided config
  ansible.builtin.debug:
    var: certs
  when:
    - debug is defined
    - debug

- name: Certificates | Showing debug info - running config
  ansible.builtin.debug:
    var: CERT_CONFIG
  when:
    - debug is defined
    - debug

- name: Certificates | Internal signed
  ansible.builtin.include_tasks: internal/main.yml
  when: "CERT_CONFIG.mode in ['pki', 'ca', 'selfsigned']"

- name: Certificates | Internal | CA
  ansible.builtin.include_tasks: debian/pki.yml
  when: CERT_CONFIG.mode == 'pki'

- name: Certificates | Debian | Letsencrypt
  ansible.builtin.include_tasks: debian/letsencrypt/main.yml
  when:
    - CERT_CONFIG.mode == 'le_certbot'
    - "ansible_distribution|lower in ['debian', 'ubuntu']"
