---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-certs-internal
    docker_networks:
      - name: 'test-ag-certs'
        ipam_config:
          - subnet: '192.168.6.0/24'
            gateway: '192.168.6.254'
    networks:
      - name: 'test-ag-certs'
        ipv4_address: '192.168.6.1'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-certs-letsencrypt
    networks:
      - name: 'test-ag-certs'
        ipv4_address: '192.168.6.2'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'
    exposed_ports:
      - '80/tcp'
    published_ports:  # proxied for LetsEncrypt tests
      - '0.0.0.0:8080:80/tcp'

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
